version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
    restart: unless-stopped

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    restart: unless-stopped
      
  api:
    build: ./server
    ports:
      - "80:9000"
    environment:
      - URL_REMOTE=google.com
    restart: unless-stopped
    volumes:
      - .:/usr/app
    depends_on:
      - db
    command: npm run start
volumes:
  data-db:
    external: true